# Generated by Django 4.2.7 on 2023-11-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-09-9'),
            preserve_default=False,
        ),
    ]
